version: "3.8"

services:
  uala-backend-challenge:
    container_name: uala-backend-challenge
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
      - redis
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_database
  redis:
    image: redis:3.2.5
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  #  networks:
  #    springboot-mysql-net:

    #networks:
    #  springboot-mysql-net:
   # restart: on-failure

#networks:
#  springboot-mysql-net: